title: Hello There!
logo: /assets/img/headshot.jpg
description: "An aspiring Engineer and Educator in the field of Computer Science, driven about research on Computer and online Security as well as Human Computer Interaction. Enthusiastic to explore the applications of Artificial Intelligence and Machine Learning in practical fields, including enhancement and protection of User Security."
show_downloads: true
theme: jekyll-theme-minimal
